# this one is important
SET(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR cortex-a53)
SET(CMAKE_SYSTEM_VERSION 1)

SET(CMAKE_C_COMPILER   /usr/bin/aarch64-linux-gnu-gcc)

SET(CMAKE_FIND_ROOT_PATH /usr/aarch64-linux-gnu)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
# end of the file

